name: Test app token

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: appToken
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ref: app-token
          token: ${{ steps.appToken.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: date >> test.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: test.txt
          message: test update
